spring.application.name=usuarios
server.port=8086

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/usuarios_microservice?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del ObjectMapper
#   Permite que el JSON body enviado desde Postman via PostMapping
#   pueda contener campos de tipo primitivo (int) como null.

#   El error se da cuando se intenta registrar un usuario sin
#   especificar su nivel de acceso, el ObjectMapper espera un
#   objeto Usuario, incluyendo el atributo nvlPermiso, si es nulo
#   no lo acepta y lo marca como error de capa 8 
spring.jackson.deserialization.fail-on-null-for-primitives=false


#Extras para pruebas unitarias
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
server.servlet.context-path=/api
springdoc.api-docs.path=/v3/api-docs